version: '3.5'

services:
  postgres-master:
    container_name: postgres-master
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DATABASE_HOST: ${DB_HOST:-postgres-master}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
    restart: unless-stopped

  postgres-replica:
    container_name: postgres-replica
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres-master
    volumes:
      - ./data-replica:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - default

  postgres-replica-2:
    container_name: postgres-replica-2
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres-master
    volumes:
      - ./data-replica-2:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - default

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@test.ru}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - default
    restart: unless-stopped

  service:
    container_name: service
    depends_on:
      - postgres-master
      - postgres-replica
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - default
    ports:
      - "4444:4444"
    environment:
      LOG_LEVEL: "info"
      DB_DSN: ${DB_DSN}
      DB_REPLICA_DSN: ${DB_REPLICA_DSN}


networks:
  postgres:
    driver: bridge

volumes:
    pgadmin:
